### ISSUE TITLE
CUDLR doesn't work with il2cpp builds

### ISSUE THREAD

**Issue by raphaelsantos** [proletariatgames/CUDLR#16]
I can't connect to the device when I build using il2cpp.

Any plans on fixing this?

Thanks!

**Comment by lpetre** [comment]
Hi @raphaelsantos, thanks for the message. We haven't built locally with il2cpp yet, we need to wait for Metal support before we upgrade.

If I get a change to try 4.6.2 + CUDLR in a test environment I'll see if I can debug the issue, but I can't promise that will be in the immediate future.

**Comment by yourpalmark** [comment]
Any update on this issue?
4.6.3 added Metal support. I have just tested on the latest patch release, 4.6.3p2 and CUDLR still doesn't work.

**Comment by dogles** [comment]
Hi, @yourpalmark, I'll be looking at migrating our codebase to IL2CPP within the next week or two, and will be fixing any issues here as part of it.
