### ISSUE TITLE
Application.RegisterLogCallback deprecated

### ISSUE THREAD

**Issue by xrix4096** [proletariatgames/CUDLR#25]
Unity 5 uses an event instead so in OnEnable() in Server.cs

`Application.RegisterLogCallback(Console.LogCallback);`

should become

`Application.logMessageReceived += Console.LogCallback;`

and OnDisable() replace

`Application.RegisterLogCallback(null);`

with

`Application.logMessageReceived -= Console.LogCallback;`

Can fork and do a PR if that helps

**Comment by xrix4096** [comment]
Just noticed @AustinSpafford already submitted a PR for this

**Comment by joemukai** [comment]
Thanks for reaching out! I merged #24
